name: Grid CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Copy APK to Release Folder
        run: |
          mkdir -p release
          cp app/build/outputs/apk/release/*.apk release/

      - name: Create GitHub Release with APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.run_number }}"
          name: "Build #${{ github.run_number }}"
          body: |
            This is an auto-generated APK build from the latest master commit.
            Commit: ${{ github.sha }}
          files: release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}